version: 2

models:
  - name: stg_questions
    description: "Cleaned and standardized Stack Overflow questions"
    columns:
      - name: question_id
        description: "Unique identifier for the question"
        tests:
          - unique
          - not_null
      - name: tags
        description: "Pipe-separated list of tags"
        tests:
          - not_null

  - name: stg_tags
    description: "Distinct list of all tags"
    columns:
      - name: tag_name
        description: "Tag name"
        tests:
          - unique
          - not_null